apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-rbac
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/Shasame/Yggdrasil.git
    targetRevision: HEAD
    path: v2/infrastructure/tailscale
    directory:
      include: "rbac.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale
  syncPolicy:
    automated:
      prune: false   # never auto-delete your cluster-admin binding
      selfHeal: true