apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflare-tunnel
data:
  config.yaml: |
  
    ingress:
      - hostname: jellyfin.shasame.fr
        service: http://traefik.traefik.svc.cluster.local:80

      - hostname: seerr.shasame.fr
        service: http://traefik.traefik.svc.cluster.local:80

      - service: http_status:404