apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  url: https://argocd.shasame.fr
  oidc.config: |
    name: Yggdrasil SSO
    issuer: https://auth.shasame.fr
    clientID: argocd
    # ArgoCD will look for a key named 'oidc.dex.clientSecret' inside the 'argocd-secret' Kubernetes Secret
    clientSecret: $oidc.dex.clientSecret 
    requestedScopes: ["openid", "profile", "email", "groups"]